project:
  type: website
  output-dir: docs

website:
  search: false
  title: "Project Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: spatial_analysis.qmd
        text: Spatial Analysis
      - href: vaers_report.qmd
        text: Severity Classification Task

format:
  html:
    theme: pulse
    css: no_stylist.css
    toc: false
    anchor-sections: false



